#!/bin/sh

# Copyright (c) 2014, Ericsson AB
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# This is a wrapper script for the new tipc configuration tool called "tipc".
# It only supports basic functionality and its sole intent is to ease the
# transition from tipc-config and the old kernel API to "tipc" and the new API.

# Note, this code is written with the intent to work on "embedded systems" where
# there is a limited set of tools and we don't know what the default shell is.

echo "WARNING: tipc-config is deprecated, use \"tipc\" instead" >&2
if which logger > /dev/null 2>&1; then
	logger -t "tipc-config" "warning, this tool is deprecated use \"tipc\" instead"
fi

if [ $# -lt 1 ]; then
	exit 1
fi

case "$1" in
	-a | -addr)
		cmd="tipc address show"
		;;
	-a=* | -addr=*)
		cmd="tipc address set $(echo $1 | cut -d'=' -s -f 2)"
		;;
	-b)
		cmd="tipc bearer list"
		;;
	-be=*)
		str=$(echo $1 | cut -d'=' -s -f 2)
		bearer=$(echo $str | cut -d'/' -f 1)

		props=$(echo $str | cut -d'/' -s -f 2-)
		dom=$(echo $props | cut -d'/' -f 1)
		prio=$(echo $props | cut -d'/' -s -f 2)

		cmd="tipc bearer enable $bearer"
		if [ ! -z $dom ]; then
			cmd="$cmd domain $dom"
		fi
		if [ ! -z $prio ]; then
			cmd="$cmd priority $prio"
		fi
		;;
	-bd=*)
		cmd="tipc bearer disable $(echo $1 | cut -d'=' -s -f 2)"
		;;
	-h)
		cmd="tipc -h"
		;;
	-l)
		cmd="tipc link list"
		;;
	-ls)
		cmd="tipc link statistics show"
		;;
	-m)
		cmd="tipc media list"
		;;
	-n)
		cmd="tipc node list"
		;;
	-nt)
		cmd="tipc nametable show"
		;;
	-netid)
		cmd="tipc net id show"
		;;
	-netid=*)
		cmd="tipc net id set $(echo $1 | cut -d'=' -s -f 2)"
		;;
	-p)
		cmd="tipc socket list"
		;;
	*)
		echo "error, unsupported or invalid command \"tipc-config $@\"" >&2
		exit 1
		;;
esac

echo "The command you are running translates to \"$cmd\"" >&2
echo >&2

$cmd
exit $?
